spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC&characterEncoding=utf-8
server:
  port: 9090